import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, "..");

async function main() {
  const packageJson = JSON.parse(await readFile(path.join(packageRoot, "package.json"), "utf8"));
  assert.equal(packageJson.name, "ai-provenance-vscode", "Unexpected extension package name.");
  assert.equal(packageJson.publisher, "tiinex", "Unexpected publisher.");
  assert.equal(packageJson.icon, "assets/logo-transparent.png", "Provenance extension icon path is missing or stale.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:list_traceable_agents"), "Provenance traceable agent catalog activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:view_traceable_subagent"), "Provenance LM tool activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:run_traceable_subagent"), "Provenance runtime LM tool activation is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "list_traceable_agents"), "Provenance traceable agent catalog contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "run_traceable_subagent"), "Provenance runtime LM tool contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "view_traceable_subagent"), "Provenance LM tool contribution is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.evidenceMaxItems"], "Provenance namespaced settings are missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableAutoReveal"], "Provenance TRACEABLE auto-reveal setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableAutoHide"], "Provenance TRACEABLE auto-hide setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceablePreferredModels"], "Provenance TRACEABLE preferred-models setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableBlockedModels"], "Provenance TRACEABLE blocked-models setting is missing.");
  assert.ok(packageJson.contributes?.views?.tiinexAiProvenanceTraceablePanel?.some((entry) => entry.id === "tiinex.aiProvenance.traceableStatus"), "Provenance TRACEABLE panel view contribution is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.openOverview"), "Overview command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.inspectTraceableEvidence"), "TRACEABLE evidence inspect command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.openTraceableEvidenceEditor"), "TRACEABLE evidence editor command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.reopenTraceableEvidenceSource"), "TRACEABLE evidence reopen-source command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.reopenTraceableEvidencePreview"), "TRACEABLE evidence reopen-preview command is missing.");
  assert.ok(!("mcp" in (packageJson.scripts ?? {})), "This scaffold should not expose an MCP script.");
  assert.ok(!Object.keys(packageJson.devDependencies ?? {}).includes("@modelcontextprotocol/sdk"), "This scaffold should not pull in MCP dependencies.");
  const bundle = await readFile(path.join(packageRoot, "dist", "extension.js"), "utf8");
  assert.ok(bundle.includes("inspectTraceableEvidence"), "Built bundle is missing the TRACEABLE evidence inspect command.");
  assert.ok(bundle.includes("openTraceableEvidenceEditor"), "Built bundle is missing the TRACEABLE evidence viewer command.");
  assert.ok(bundle.includes("reopenTraceableEvidenceSource"), "Built bundle is missing the TRACEABLE evidence reopen-source command.");
  assert.ok(bundle.includes("reopenTraceableEvidencePreview"), "Built bundle is missing the TRACEABLE evidence reopen-preview command.");
  assert.ok(bundle.includes("run_traceable_subagent"), "Built bundle is missing the provenance TRACEABLE runtime tool wiring.");
  assert.ok(bundle.includes("list_traceable_agents"), "Built bundle is missing the provenance traceable agent catalog tool wiring.");
  assert.ok(bundle.includes("openTraceableSubagentStatusDetail"), "Built bundle is missing the provenance TRACEABLE panel reveal command.");
  assert.ok(bundle.includes("tiinex.aiProvenance.traceableStatus"), "Built bundle is missing the provenance TRACEABLE panel view id.");
  assert.ok(bundle.includes("Tool Ledger"), "Built bundle is missing the TRACEABLE evidence surface picker labels.");
  assert.ok(bundle.includes("Rendered Output"), "Built bundle is missing the moved traceable rendered-output label.");
  assert.ok(bundle.includes("hideToolbarControls"), "Built bundle is missing the restored TRACEABLE evidence panel renderer wiring.");
  assert.ok(bundle.includes("tiinexTraceableEvidenceEditor"), "Built bundle is missing the restored TRACEABLE evidence editor view type.");
  assert.ok(bundle.includes("view_traceable_subagent"), "Built bundle is missing the provenance LM tool wiring.");
  const source = await readFile(path.join(packageRoot, "src", "traceableEvidence.ts"), "utf8");
  assert.ok(source.includes("TRACEABLE_EVIDENCE_STATE_SCHEMA"), "Traceable evidence parser source is missing the schema constant.");
  assert.ok(source.includes("renderTraceableEvidenceToolLedgerMarkdown"), "Traceable evidence source is missing the bounded tool-ledger renderer.");
  assert.ok(source.includes("renderViewTraceableSubagentMarkdown"), "Traceable evidence source is missing the moved traceable view renderer.");
  const panelSource = await readFile(path.join(packageRoot, "src", "traceableSubagentStatusPanel.ts"), "utf8");
  assert.ok(panelSource.includes("export function renderTraceableSubagentPanelHtml"), "Traceable panel source is missing the restored committed viewer renderer.");
  assert.ok(panelSource.includes("hideToolbarControls"), "Traceable panel source is missing the restored viewer toolbar-control behavior.");
  assert.ok(panelSource.includes("tiinex.aiProvenance.traceableStatus"), "Traceable panel source is missing the provenance panel view id.");
  const runtimeSource = await readFile(path.join(packageRoot, "src", "traceableSubagent.ts"), "utf8");
  assert.ok(runtimeSource.includes("tiinex.aiProvenance"), "Traceable runtime source is missing the provenance configuration namespace.");
  assert.ok(runtimeSource.includes("export async function runTraceableSubagent"), "Traceable runtime source is missing the moved runtime entrypoint.");
  assert.ok(runtimeSource.includes("export async function listTraceableAgentCatalogEntries"), "Traceable runtime source is missing the moved traceable agent catalog entries export.");
  assert.ok(runtimeSource.includes("\\bcomplete(?:d)?\\b"), "Traceable runtime source is missing the broader completed stop-reason normalization that accepts natural-language child summaries.");
  const contractSource = await readFile(path.join(packageRoot, "src", "traceableContract.ts"), "utf8");
  assert.ok(contractSource.includes("export interface TraceableSubagentRunResult"), "Traceable contract source is missing the run result contract.");
  assert.ok(contractSource.includes("normalizeTraceableOutputMode"), "Traceable contract source is missing output-mode normalization.");
  assert.ok(contractSource.includes("buildTraceableSubagentRequestEnvelope"), "Traceable contract source is missing request-envelope construction.");
  assert.ok(contractSource.includes("resolveTraceableParentFrame"), "Traceable contract source is missing parent-frame resolution.");
  assert.ok(contractSource.includes("extractTraceableSubagentPayload"), "Traceable contract source is missing payload extraction.");
  assert.ok(contractSource.includes("normalizeParsedPayload"), "Traceable contract source is missing payload normalization.");
  assert.ok(contractSource.includes("resolveTraceStatus"), "Traceable contract source is missing trace-status resolution.");
  assert.ok(contractSource.includes("buildUnparseableChildPayloadFallback"), "Traceable contract source is missing unparseable-payload fallback construction.");
  assert.ok(contractSource.includes("collectTraceableInputValidationIssues"), "Traceable contract source is missing input validation helpers.");
  assert.ok(contractSource.includes("renderTraceableSubagentEvidencePathOnly"), "Traceable contract source is missing evidence-path-only markdown rendering.");
  assert.ok(contractSource.includes("formatTraceablePathReference"), "Traceable contract source is missing path-reference rendering.");
  assert.ok(contractSource.includes("renderTraceableSubagentMarkdown"), "Traceable contract source is missing full markdown rendering.");
  assert.ok(contractSource.includes("appendBoundedJsonPreview"), "Traceable contract source is missing bounded JSON previews.");
  assert.ok(contractSource.includes("extractObservedReadTargets"), "Traceable contract source is missing observed-read target summaries.");
  console.log("ai-provenance vscode scaffold checks passed");
}

await main();