import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, "..");

async function main() {
  const packageJson = JSON.parse(await readFile(path.join(packageRoot, "package.json"), "utf8"));
  assert.equal(packageJson.name, "ai-provenance-vscode", "Unexpected extension package name.");
  assert.equal(packageJson.publisher, "tiinex", "Unexpected publisher.");
  assert.equal(packageJson.icon, "assets/logo-transparent.png", "Provenance extension icon path is missing or stale.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:list_traceable_agents"), "Provenance traceable agent catalog activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:list_traceable_models"), "Provenance traceable model catalog activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:view_traceable_subagent"), "Provenance LM tool activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:run_traceable_subagent"), "Provenance runtime LM tool activation is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "list_traceable_agents"), "Provenance traceable agent catalog contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "list_traceable_models"), "Provenance traceable model catalog contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "run_traceable_subagent"), "Provenance runtime LM tool contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "view_traceable_subagent"), "Provenance LM tool contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "run_traceable_subagent")?.modelDescription?.includes("Canonical usage:"), "run_traceable_subagent is missing canonical usage guidance in the public tool description.");
  assert.ok(packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "list_traceable_models")?.modelDescription?.includes("sendableOnly: true"), "list_traceable_models is missing exact preflight guidance in the public tool description.");
  assert.ok(packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "view_traceable_subagent")?.modelDescription?.includes("Prefer this over rerunning the same child lane"), "view_traceable_subagent is missing inspect-before-rerun guidance in the public tool description.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.evidenceMaxItems"], "Provenance namespaced settings are missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableAutoReveal"], "Provenance TRACEABLE auto-reveal setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableAutoHide"], "Provenance TRACEABLE auto-hide setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceablePreferredModels"], "Provenance TRACEABLE preferred-models setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableBlockedModels"], "Provenance TRACEABLE blocked-models setting is missing.");
  assert.ok(packageJson.contributes?.views?.tiinexAiProvenanceTraceablePanel?.some((entry) => entry.id === "tiinex.aiProvenance.traceableStatus"), "Provenance TRACEABLE panel view contribution is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.openOverview"), "Overview command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.inspectTraceableEvidence"), "TRACEABLE evidence inspect command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.openTraceableEvidenceEditor"), "TRACEABLE evidence editor command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.reopenTraceableEvidenceSource"), "TRACEABLE evidence reopen-source command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.reopenTraceableEvidencePreview"), "TRACEABLE evidence reopen-preview command is missing.");
  assert.ok(!("mcp" in (packageJson.scripts ?? {})), "This scaffold should not expose an MCP script.");
  assert.ok(!Object.keys(packageJson.devDependencies ?? {}).includes("@modelcontextprotocol/sdk"), "This scaffold should not pull in MCP dependencies.");
  const bundle = await readFile(path.join(packageRoot, "dist", "extension.js"), "utf8");
  assert.ok(bundle.includes("inspectTraceableEvidence"), "Built bundle is missing the TRACEABLE evidence inspect command.");
  assert.ok(bundle.includes("openTraceableEvidenceEditor"), "Built bundle is missing the TRACEABLE evidence viewer command.");
  assert.ok(bundle.includes("reopenTraceableEvidenceSource"), "Built bundle is missing the TRACEABLE evidence reopen-source command.");
  assert.ok(bundle.includes("reopenTraceableEvidencePreview"), "Built bundle is missing the TRACEABLE evidence reopen-preview command.");
  assert.ok(bundle.includes("run_traceable_subagent"), "Built bundle is missing the provenance TRACEABLE runtime tool wiring.");
  assert.ok(bundle.includes("list_traceable_agents"), "Built bundle is missing the provenance traceable agent catalog tool wiring.");
  assert.ok(bundle.includes("list_traceable_models"), "Built bundle is missing the provenance traceable model catalog tool wiring.");
  assert.ok(bundle.includes("Preferred matches"), "Built bundle is missing the traceable model policy summary rendering.");
  assert.ok(bundle.includes("Policy:"), "Built bundle is missing per-model policy flag rendering.");
  assert.ok(bundle.includes("Recommended flow:"), "Built bundle is missing embedded workflow guidance for traceable catalog tools.");
  assert.ok(bundle.includes("Typical next step:"), "Built bundle is missing the canonical next-step guidance for the traceable model catalog.");
  assert.ok(bundle.includes("openTraceableSubagentStatusDetail"), "Built bundle is missing the provenance TRACEABLE panel reveal command.");
  assert.ok(bundle.includes("tiinex.aiProvenance.traceableStatus"), "Built bundle is missing the provenance TRACEABLE panel view id.");
  assert.ok(bundle.includes("Tool Ledger"), "Built bundle is missing the TRACEABLE evidence surface picker labels.");
  assert.ok(bundle.includes("Rendered Output"), "Built bundle is missing the moved traceable rendered-output label.");
  assert.ok(bundle.includes("hideToolbarControls"), "Built bundle is missing the restored TRACEABLE evidence panel renderer wiring.");
  assert.ok(bundle.includes("tiinexTraceableEvidenceEditor"), "Built bundle is missing the restored TRACEABLE evidence editor view type.");
  assert.ok(bundle.includes("view_traceable_subagent"), "Built bundle is missing the provenance LM tool wiring.");
  const source = await readFile(path.join(packageRoot, "src", "traceableEvidence.ts"), "utf8");
  assert.ok(source.includes("TRACEABLE_EVIDENCE_STATE_SCHEMA"), "Traceable evidence parser source is missing the schema constant.");
  assert.ok(source.includes("renderTraceableEvidenceToolLedgerMarkdown"), "Traceable evidence source is missing the bounded tool-ledger renderer.");
  assert.ok(source.includes("renderViewTraceableSubagentMarkdown"), "Traceable evidence source is missing the moved traceable view renderer.");
  const panelSource = await readFile(path.join(packageRoot, "src", "traceableSubagentStatusPanel.ts"), "utf8");
  assert.ok(panelSource.includes("export function renderTraceableSubagentPanelHtml"), "Traceable panel source is missing the restored committed viewer renderer.");
  assert.ok(panelSource.includes("hideToolbarControls"), "Traceable panel source is missing the restored viewer toolbar-control behavior.");
  assert.ok(panelSource.includes("tiinex.aiProvenance.traceableStatus"), "Traceable panel source is missing the provenance panel view id.");
  const runtimeSource = await readFile(path.join(packageRoot, "src", "traceableSubagent.ts"), "utf8");
  assert.ok(runtimeSource.includes("tiinex.aiProvenance"), "Traceable runtime source is missing the provenance configuration namespace.");
  assert.ok(runtimeSource.includes("export async function runTraceableSubagent"), "Traceable runtime source is missing the moved runtime entrypoint.");
  assert.ok(runtimeSource.includes("export async function listTraceableAgentCatalogEntries"), "Traceable runtime source is missing the moved traceable agent catalog entries export.");
  assert.ok(runtimeSource.includes("export async function listTraceableModelCatalogEntries"), "Traceable runtime source is missing the moved traceable model catalog entries export.");
  assert.ok(runtimeSource.includes("copilot/gpt-4.1"), "Traceable runtime source is missing the supported copilot/gpt-4.1 declaration for preferred-model configuration.");
  assert.ok(runtimeSource.includes("\"gpt-5.5\", { vendor: \"copilot\", id: \"gpt-5.5\" }"), "Traceable runtime source is missing bare human-label support for role models such as GPT-5.5.");
  assert.ok(runtimeSource.includes("\"claude-sonnet-4.5\", { vendor: \"copilot\", id: \"claude-sonnet-4.5\" }"), "Traceable runtime source is missing bare human-label support for role models such as Claude Sonnet 4.5.");
  assert.ok(runtimeSource.includes("\"raptor-mini-preview\", { vendor: \"copilot\", id: \"oswe-vscode-prime\" }"), "Traceable runtime source is missing bare human-label support for role models such as Raptor mini (Preview).");
  assert.ok(runtimeSource.includes("copilotgpt-4.1"), "Traceable runtime source is missing the normalized exact lookup form for copilot/gpt-4.1 settings.");
  assert.ok(runtimeSource.includes("copilot/gpt-5.5"), "Traceable runtime source is missing the supported copilot/gpt-5.5 declaration for blocked-model configuration.");
  assert.ok(runtimeSource.includes("copilotgpt-5.5"), "Traceable runtime source is missing the normalized exact lookup form for copilot/gpt-5.5 settings.");
  assert.ok(runtimeSource.includes("copilot/oswe-vscode-prime"), "Traceable runtime source is missing the supported copilot/oswe-vscode-prime declaration for low-cost preferred-model configuration.");
  assert.ok(runtimeSource.includes("copilotoswe-vscode-prime"), "Traceable runtime source is missing the normalized exact lookup form for copilot/oswe-vscode-prime settings.");
  assert.ok(runtimeSource.includes("Explicit modelSelector.id is blocked by tiinex.aiProvenance.traceableBlockedModels"), "Traceable runtime source is missing explicit blocked-model rejection.");
  assert.ok(runtimeSource.includes("Math.random() * (index + 1)"), "Traceable runtime source is missing selector shuffling for preferred and role model pools.");
  assert.ok(runtimeSource.includes("value === true"), "Traceable runtime source is missing boolean completion-claim normalization for child JSON payloads.");
  assert.ok(runtimeSource.includes("no further reads needed"), "Traceable runtime source is missing natural-language completed stop-reason normalization for child JSON payloads.");
  assert.ok(runtimeSource.includes("sufficient per contract"), "Traceable runtime source is missing completed stop-reason normalization for minimal-read contract phrasing.");
  assert.ok(runtimeSource.includes("\\bcomplete(?:d)?\\b"), "Traceable runtime source is missing the broader completed stop-reason normalization that accepts natural-language child summaries.");
  const evidenceExportSource = await readFile(path.join(packageRoot, "src", "traceableSubagentEvidence.ts"), "utf8");
  assert.ok(evidenceExportSource.includes("renameEvidenceFileForSnapshot"), "Traceable evidence export source is missing evidence-file rename support when the final role or model label becomes known after export begins.");
  const contractSource = await readFile(path.join(packageRoot, "src", "traceableContract.ts"), "utf8");
  assert.ok(contractSource.includes("export interface TraceableSubagentRunResult"), "Traceable contract source is missing the run result contract.");
  assert.ok(contractSource.includes("normalizeTraceableOutputMode"), "Traceable contract source is missing output-mode normalization.");
  assert.ok(contractSource.includes("buildTraceableSubagentRequestEnvelope"), "Traceable contract source is missing request-envelope construction.");
  assert.ok(contractSource.includes("resolveTraceableParentFrame"), "Traceable contract source is missing parent-frame resolution.");
  assert.ok(contractSource.includes("extractTraceableSubagentPayload"), "Traceable contract source is missing payload extraction.");
  assert.ok(contractSource.includes("normalizeParsedPayload"), "Traceable contract source is missing payload normalization.");
  assert.ok(contractSource.includes("resolveTraceStatus"), "Traceable contract source is missing trace-status resolution.");
  assert.ok(contractSource.includes("buildUnparseableChildPayloadFallback"), "Traceable contract source is missing unparseable-payload fallback construction.");
  assert.ok(contractSource.includes("collectTraceableInputValidationIssues"), "Traceable contract source is missing input validation helpers.");
  assert.ok(contractSource.includes("renderTraceableSubagentEvidencePathOnly"), "Traceable contract source is missing evidence-path-only markdown rendering.");
  assert.ok(contractSource.includes("formatTraceablePathReference"), "Traceable contract source is missing path-reference rendering.");
  assert.ok(contractSource.includes("renderTraceableSubagentMarkdown"), "Traceable contract source is missing full markdown rendering.");
  assert.ok(contractSource.includes("appendBoundedJsonPreview"), "Traceable contract source is missing bounded JSON previews.");
  assert.ok(contractSource.includes("extractObservedReadTargets"), "Traceable contract source is missing observed-read target summaries.");
  console.log("ai-provenance vscode scaffold checks passed");
}

await main();