import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, "..");

async function main() {
  const packageJson = JSON.parse(await readFile(path.join(packageRoot, "package.json"), "utf8"));
  assert.equal(packageJson.name, "ai-provenance", "Unexpected extension package name.");
  assert.equal(packageJson.publisher, "tiinex", "Unexpected publisher.");
  assert.equal(packageJson.icon, "assets/logo-transparent.png", "Provenance extension icon path is missing or stale.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:list_traceable_agents"), "Provenance traceable agent catalog activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:list_traceable_models"), "Provenance traceable model catalog activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:view_traceable_subagent"), "Provenance LM tool activation is missing.");
  assert.ok(packageJson.activationEvents?.includes("onLanguageModelTool:run_traceable_subagent"), "Provenance runtime LM tool activation is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "list_traceable_agents"), "Provenance traceable agent catalog contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "list_traceable_models"), "Provenance traceable model catalog contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "run_traceable_subagent"), "Provenance runtime LM tool contribution is missing.");
  assert.ok(packageJson.contributes?.languageModelTools?.some((entry) => entry.name === "view_traceable_subagent"), "Provenance LM tool contribution is missing.");
  const runTraceableTool = packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "run_traceable_subagent");
  assert.ok(runTraceableTool?.inputSchema?.properties?.parentTracePath, "run_traceable_subagent is missing the public parentTracePath continuation input schema property.");
  assert.ok(runTraceableTool?.inputSchema?.properties?.exportToFolder, "run_traceable_subagent is missing the public exportToFolder input schema property.");
  assert.ok(runTraceableTool?.inputSchema?.properties?.outputMode, "run_traceable_subagent is missing the public outputMode input schema property.");
  assert.ok(runTraceableTool?.inputSchema?.properties?.inputMode, "run_traceable_subagent is missing the public inputMode input schema property.");
  assert.ok(runTraceableTool?.inputSchema?.properties?.validationMode, "run_traceable_subagent is missing the public validationMode input schema property.");
  assert.ok(runTraceableTool?.inputSchema?.properties?.reveal, "run_traceable_subagent is missing the public reveal input schema property.");
  assert.ok(runTraceableTool?.inputSchema?.properties?.inputMode?.enum?.includes("DIRECT"), "run_traceable_subagent is missing the public DIRECT inputMode variant.");
  assert.ok(runTraceableTool?.inputSchema?.properties?.inputMode?.enum?.includes("RESUME"), "run_traceable_subagent is missing the public RESUME inputMode variant.");
  assert.deepEqual(runTraceableTool?.inputSchema?.required ?? [], [], "run_traceable_subagent should not hard-require userInput and parentTask for every inputMode.");
  assert.ok(packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "run_traceable_subagent")?.modelDescription?.includes("Canonical usage:"), "run_traceable_subagent is missing canonical usage guidance in the public tool description.");
  assert.ok(packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "run_traceable_subagent")?.modelDescription?.includes("artifact-backed continuation"), "run_traceable_subagent is missing truthful continuation guidance in the public tool description.");
  assert.ok(packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "list_traceable_models")?.modelDescription?.includes("sendableOnly: true"), "list_traceable_models is missing exact preflight guidance in the public tool description.");
  assert.ok(packageJson.contributes?.languageModelTools?.find((entry) => entry.name === "view_traceable_subagent")?.modelDescription?.includes("Prefer this over rerunning the same child lane"), "view_traceable_subagent is missing inspect-before-rerun guidance in the public tool description.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.evidenceMaxItems"], "Provenance namespaced settings are missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableAutoReveal"], "Provenance TRACEABLE auto-reveal setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableAutoHide"], "Provenance TRACEABLE auto-hide setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceablePreferredModels"], "Provenance TRACEABLE preferred-models setting is missing.");
  assert.ok(packageJson.contributes?.configuration?.properties?.["tiinex.aiProvenance.traceableBlockedModels"], "Provenance TRACEABLE blocked-models setting is missing.");
  assert.ok(packageJson.contributes?.views?.tiinexAiProvenanceTraceablePanel?.some((entry) => entry.id === "tiinex.aiProvenance.traceableStatus"), "Provenance TRACEABLE panel view contribution is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.openOverview"), "Overview command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.inspectTraceableEvidence"), "TRACEABLE evidence inspect command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.stopTraceableSubagent"), "TRACEABLE stop command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.openTraceableEvidenceEditor"), "TRACEABLE evidence editor command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.reopenTraceableEvidenceSource"), "TRACEABLE evidence reopen-source command is missing.");
  assert.ok(packageJson.contributes?.commands?.some((entry) => entry.command === "tiinex.aiProvenance.reopenTraceableEvidencePreview"), "TRACEABLE evidence reopen-preview command is missing.");
  assert.ok(!("mcp" in (packageJson.scripts ?? {})), "This scaffold should not expose an MCP script.");
  assert.ok(!Object.keys(packageJson.devDependencies ?? {}).includes("@modelcontextprotocol/sdk"), "This scaffold should not pull in MCP dependencies.");
  const bundle = await readFile(path.join(packageRoot, "dist", "extension.js"), "utf8");
  assert.ok(bundle.includes("inspectTraceableEvidence"), "Built bundle is missing the TRACEABLE evidence inspect command.");
  assert.ok(bundle.includes("openTraceableEvidenceEditor"), "Built bundle is missing the TRACEABLE evidence viewer command.");
  assert.ok(bundle.includes("reopenTraceableEvidenceSource"), "Built bundle is missing the TRACEABLE evidence reopen-source command.");
  assert.ok(bundle.includes("reopenTraceableEvidencePreview"), "Built bundle is missing the TRACEABLE evidence reopen-preview command.");
  assert.ok(bundle.includes("run_traceable_subagent"), "Built bundle is missing the provenance TRACEABLE runtime tool wiring.");
  assert.ok(bundle.includes("list_traceable_agents"), "Built bundle is missing the provenance traceable agent catalog tool wiring.");
  assert.ok(bundle.includes("list_traceable_models"), "Built bundle is missing the provenance traceable model catalog tool wiring.");
  assert.ok(bundle.includes("Preferred matches"), "Built bundle is missing the traceable model policy summary rendering.");
  assert.ok(bundle.includes("Policy:"), "Built bundle is missing per-model policy flag rendering.");
  assert.ok(bundle.includes("Recommended flow:"), "Built bundle is missing embedded workflow guidance for traceable catalog tools.");
  assert.ok(bundle.includes("Typical next step:"), "Built bundle is missing the canonical next-step guidance for the traceable model catalog.");
  assert.ok(bundle.includes("openTraceableSubagentStatusDetail"), "Built bundle is missing the provenance TRACEABLE panel reveal command.");
  assert.ok(bundle.includes("stopTraceableSubagent"), "Built bundle is missing the provenance TRACEABLE stop command.");
  assert.ok(bundle.includes("tiinex.aiProvenance.traceableStatus"), "Built bundle is missing the provenance TRACEABLE panel view id.");
  assert.ok(bundle.includes("Tool Ledger"), "Built bundle is missing the TRACEABLE evidence surface picker labels.");
  assert.ok(bundle.includes("Rendered Output"), "Built bundle is missing the moved traceable rendered-output label.");
  assert.ok(bundle.includes("hideToolbarControls"), "Built bundle is missing the restored TRACEABLE evidence panel renderer wiring.");
  assert.ok(bundle.includes("tiinexTraceableEvidenceEditor"), "Built bundle is missing the restored TRACEABLE evidence editor view type.");
  assert.ok(bundle.includes("view_traceable_subagent"), "Built bundle is missing the provenance LM tool wiring.");
  assert.ok(bundle.includes("## Lineage"), "Built bundle is missing the evidence lineage observability section.");
  assert.ok(bundle.includes("### Direct Children"), "Built bundle is missing direct-child lineage rendering in evidence views.");
  assert.ok(bundle.includes("Carry State"), "Built bundle is missing the separate carry-state request summary label.");
  const source = await readFile(path.join(packageRoot, "src", "traceableEvidence.ts"), "utf8");
  assert.ok(source.includes("TRACEABLE_EVIDENCE_STATE_SCHEMA"), "Traceable evidence parser source is missing the schema constant.");
  assert.ok(source.includes("renderTraceableEvidenceToolLedgerMarkdown"), "Traceable evidence source is missing the bounded tool-ledger renderer.");
  assert.ok(source.includes("renderViewTraceableSubagentMarkdown"), "Traceable evidence source is missing the moved traceable view renderer.");
  assert.ok(source.includes("buildTraceableEvidenceLineageLines"), "Traceable evidence source is missing the derived lineage observability helper.");
  assert.ok(source.includes("Direct Children"), "Traceable evidence source is missing direct-child lineage labels.");
  const panelSource = await readFile(path.join(packageRoot, "src", "traceableSubagentStatusPanel.ts"), "utf8");
  assert.ok(panelSource.includes("export function renderTraceableSubagentPanelHtml"), "Traceable panel source is missing the restored committed viewer renderer.");
  assert.ok(panelSource.includes("hideToolbarControls"), "Traceable panel source is missing the restored viewer toolbar-control behavior.");
  assert.ok(panelSource.includes("tiinex.aiProvenance.traceableStatus"), "Traceable panel source is missing the provenance panel view id.");
  const runtimeSource = await readFile(path.join(packageRoot, "src", "traceableSubagent.ts"), "utf8");
  assert.ok(runtimeSource.includes("tiinex.aiProvenance"), "Traceable runtime source is missing the provenance configuration namespace.");
  assert.ok(runtimeSource.includes("export async function runTraceableSubagent"), "Traceable runtime source is missing the moved runtime entrypoint.");
  assert.ok(runtimeSource.includes("export async function listTraceableAgentCatalogEntries"), "Traceable runtime source is missing the moved traceable agent catalog entries export.");
  assert.ok(runtimeSource.includes("export async function listTraceableModelCatalogEntries"), "Traceable runtime source is missing the moved traceable model catalog entries export.");
  assert.ok(runtimeSource.includes("copilot/gpt-4.1"), "Traceable runtime source is missing the supported copilot/gpt-4.1 declaration for preferred-model configuration.");
  assert.ok(runtimeSource.includes("\"gpt-5.5\", { vendor: \"copilot\", id: \"gpt-5.5\" }"), "Traceable runtime source is missing bare human-label support for role models such as GPT-5.5.");
  assert.ok(runtimeSource.includes("\"claude-sonnet-4.5\", { vendor: \"copilot\", id: \"claude-sonnet-4.5\" }"), "Traceable runtime source is missing bare human-label support for role models such as Claude Sonnet 4.5.");
  assert.ok(runtimeSource.includes("\"raptor-mini-preview\", { vendor: \"copilot\", id: \"oswe-vscode-prime\" }"), "Traceable runtime source is missing bare human-label support for role models such as Raptor mini (Preview).");
  assert.ok(runtimeSource.includes("copilotgpt-4.1"), "Traceable runtime source is missing the normalized exact lookup form for copilot/gpt-4.1 settings.");
  assert.ok(runtimeSource.includes("copilot/gpt-5.5"), "Traceable runtime source is missing the supported copilot/gpt-5.5 declaration for blocked-model configuration.");
  assert.ok(runtimeSource.includes("copilotgpt-5.5"), "Traceable runtime source is missing the normalized exact lookup form for copilot/gpt-5.5 settings.");
  assert.ok(runtimeSource.includes("copilot/oswe-vscode-prime"), "Traceable runtime source is missing the supported copilot/oswe-vscode-prime declaration for low-cost preferred-model configuration.");
  assert.ok(runtimeSource.includes("copilotoswe-vscode-prime"), "Traceable runtime source is missing the normalized exact lookup form for copilot/oswe-vscode-prime settings.");
  assert.ok(runtimeSource.includes("Explicit modelSelector.id is blocked by tiinex.aiProvenance.traceableBlockedModels"), "Traceable runtime source is missing explicit blocked-model rejection.");
  assert.ok(runtimeSource.includes("Math.random() * (index + 1)"), "Traceable runtime source is missing selector shuffling for preferred and role model pools.");
  assert.ok(runtimeSource.includes("value === true"), "Traceable runtime source is missing boolean completion-claim normalization for child JSON payloads.");
  assert.ok(runtimeSource.includes("stopReason === \"budget_exhausted\" || stopReason === \"insufficient_grounding\""), "Traceable runtime source is missing completion-claim reconciliation for budget or grounding stops.");
  assert.ok(runtimeSource.includes("user_cancelled"), "Traceable runtime source is missing the user_cancelled stop-reason handling for cancellation-aware runs.");
  assert.ok(runtimeSource.includes("options.token?.isCancellationRequested"), "Traceable runtime source is missing explicit cancellation checks for the active run token.");
  assert.ok(runtimeSource.includes("stoppedBy: extra.stoppedBy"), "Traceable runtime source is missing fallback stoppedBy preservation for cancellation-aware runs.");
  assert.ok(runtimeSource.includes("stopSource: extra.stopSource"), "Traceable runtime source is missing fallback stopSource preservation for cancellation-aware runs.");
  assert.ok(runtimeSource.includes("stopRequestedAt: extra.stopRequestedAt"), "Traceable runtime source is missing fallback stopRequestedAt preservation for cancellation-aware runs.");
  assert.ok(runtimeSource.includes("activeCarryForward?: TraceableCarryForwardState"), "Traceable runtime source is missing the separate active carry-forward contract.");
  assert.ok(runtimeSource.includes("Active carry-forward state for this run"), "Traceable runtime source is missing prompt grounding for active carry-forward state.");
  assert.ok(runtimeSource.includes("activeCarryForward: parsedPayload.activeCarryForward"), "Traceable runtime source is missing child-payload carry-forward mapping into the final run result.");
  assert.ok(runtimeSource.includes("recoverableCarryState: parsedPayload.recoverableCarryState"), "Traceable runtime source is missing child-payload recoverable carry-state mapping into the final run result.");
  assert.ok(runtimeSource.includes("carryStateDisposition: parsedPayload.carryStateDisposition"), "Traceable runtime source is missing child-payload carry disposition mapping into the final run result.");
  assert.ok(runtimeSource.includes("export async function prepareTraceableSubagentInput"), "Traceable runtime source is missing the public continuation-input preparation helper.");
  assert.ok(runtimeSource.includes('"DIRECT" | "RESUME"'), "Traceable runtime source is missing the DIRECT/RESUME inputMode contract.");
  assert.ok(runtimeSource.includes("TRACEABLE DIRECT mode requires a non-empty userInput."), "Traceable runtime source is missing DIRECT-mode userInput enforcement.");
  assert.ok(runtimeSource.includes("TRACEABLE RESUME mode requires parentTracePath."), "Traceable runtime source is missing RESUME-mode parentTracePath enforcement.");
  assert.ok(runtimeSource.includes("TRACEABLE RESUME mode does not allow userInput, parentTask, or parentFrame."), "Traceable runtime source is missing strict RESUME prompt rejection.");
  assert.ok(runtimeSource.includes("parseTraceableEvidenceStateMarkdown"), "Traceable runtime source is missing readable parent evidence parsing for continuation.");
  assert.ok(runtimeSource.includes("continuedFromParent: true"), "Traceable runtime source is missing continuation metadata for child runs.");
  assert.ok(runtimeSource.includes("lineageLabel"), "Traceable runtime source is missing lineage metadata handling for continuation runs.");
  assert.ok(runtimeSource.includes("function canonicalizeExplicitTraceableModelSelector"), "Traceable runtime source is missing explicit model-selector canonicalization through the supported declaration map.");
  assert.ok(runtimeSource.includes("inferModelSelectorFromDeclaration(selector.id)"), "Traceable runtime source is missing explicit selector fallback canonicalization by bare model id.");
  assert.ok(runtimeSource.includes("function normalizeFinalSummaryValue"), "Traceable runtime source is missing tolerant finalSummary normalization for child JSON payloads.");
  assert.ok(runtimeSource.includes("no further reads needed"), "Traceable runtime source is missing natural-language completed stop-reason normalization for child JSON payloads.");
  assert.ok(runtimeSource.includes("sufficient per contract"), "Traceable runtime source is missing completed stop-reason normalization for minimal-read contract phrasing.");
  assert.ok(runtimeSource.includes("\\bcomplete(?:d)?\\b"), "Traceable runtime source is missing the broader completed stop-reason normalization that accepts natural-language child summaries.");
  const evidenceExportSource = await readFile(path.join(packageRoot, "src", "traceableSubagentEvidence.ts"), "utf8");
  assert.ok(evidenceExportSource.includes("renameEvidenceFileForSnapshot"), "Traceable evidence export source is missing evidence-file rename support when the final role or model label becomes known after export begins.");
  assert.ok(evidenceExportSource.includes("stoppedBy: result.stoppedBy"), "Traceable evidence export source is missing stoppedBy persistence for cancellation-aware runs.");
  assert.ok(evidenceExportSource.includes("stopSource: result.stopSource"), "Traceable evidence export source is missing stopSource persistence for cancellation-aware runs.");
  assert.ok(evidenceExportSource.includes("stopRequestedAt: result.stopRequestedAt"), "Traceable evidence export source is missing stopRequestedAt persistence for cancellation-aware runs.");
  assert.ok(evidenceExportSource.includes("activeCarryForward: result.activeCarryForward"), "Traceable evidence export source is missing active carry-forward persistence.");
  assert.ok(evidenceExportSource.includes("recoverableCarryState: result.recoverableCarryState"), "Traceable evidence export source is missing recoverable carry-state persistence.");
  assert.ok(evidenceExportSource.includes("continuedFromParent: result.continuedFromParent"), "Traceable evidence export source is missing continuation metadata persistence for child runs.");
  assert.ok(evidenceExportSource.includes("allocateContinuationEvidenceFilePath"), "Traceable evidence export source is missing continuation-aware evidence file allocation.");
  const contractSource = await readFile(path.join(packageRoot, "src", "traceableContract.ts"), "utf8");
  assert.ok(contractSource.includes("export interface TraceableSubagentRunResult"), "Traceable contract source is missing the run result contract.");
  assert.ok(contractSource.includes("normalizeTraceableOutputMode"), "Traceable contract source is missing output-mode normalization.");
  assert.ok(contractSource.includes("buildTraceableSubagentRequestEnvelope"), "Traceable contract source is missing request-envelope construction.");
  assert.ok(contractSource.includes("resolveTraceableParentFrame"), "Traceable contract source is missing parent-frame resolution.");
  assert.ok(contractSource.includes("extractTraceableSubagentPayload"), "Traceable contract source is missing payload extraction.");
  assert.ok(contractSource.includes("normalizeParsedPayload"), "Traceable contract source is missing payload normalization.");
  assert.ok(contractSource.includes("function normalizeFinalSummaryValue"), "Traceable contract source is missing tolerant finalSummary normalization.");
  assert.ok(contractSource.includes("resolveTraceStatus"), "Traceable contract source is missing trace-status resolution.");
  assert.ok(contractSource.includes("user_cancelled"), "Traceable contract source is missing the user_cancelled stop-reason contract.");
  assert.ok(contractSource.includes("parentTracePath?: string"), "Traceable contract source is missing parentTracePath on the public continuation surface.");
  assert.ok(contractSource.includes("continuedFromParent?: boolean"), "Traceable contract source is missing continuedFromParent metadata on the run result.");
  assert.ok(contractSource.includes("lineageDepth?: number"), "Traceable contract source is missing lineageDepth metadata on the run result.");
  assert.ok(contractSource.includes("lineageLabel?: string"), "Traceable contract source is missing lineageLabel metadata on the run result.");
  assert.ok(contractSource.includes("buildUnparseableChildPayloadFallback"), "Traceable contract source is missing unparseable-payload fallback construction.");
  assert.ok(contractSource.includes("collectTraceableInputValidationIssues"), "Traceable contract source is missing input validation helpers.");
  assert.ok(contractSource.includes('"DIRECT" | "RESUME"'), "Traceable contract source is missing the DIRECT/RESUME inputMode contract.");
  assert.ok(contractSource.includes("renderTraceableSubagentEvidencePathOnly"), "Traceable contract source is missing evidence-path-only markdown rendering.");
  assert.ok(contractSource.includes("formatTraceablePathReference"), "Traceable contract source is missing path-reference rendering.");
  assert.ok(contractSource.includes("renderTraceableSubagentMarkdown"), "Traceable contract source is missing full markdown rendering.");
  assert.ok(contractSource.includes("appendBoundedJsonPreview"), "Traceable contract source is missing bounded JSON previews.");
  assert.ok(contractSource.includes("stoppedBy?: \"user\" | \"host\""), "Traceable contract source is missing stoppedBy metadata on the run result.");
  assert.ok(contractSource.includes("stopSource?: \"traceable-panel\" | \"host-cancel\" | \"unknown\""), "Traceable contract source is missing stopSource metadata on the run result.");
  assert.ok(contractSource.includes("stopRequestedAt?: string"), "Traceable contract source is missing stopRequestedAt metadata on the run result.");
  assert.ok(contractSource.includes("export interface TraceableCarryForwardState"), "Traceable contract source is missing the carry-forward state contract.");
  assert.ok(contractSource.includes("activeCarryForward?: TraceableCarryForwardState"), "Traceable contract source is missing the active carry-forward field.");
  assert.ok(contractSource.includes("carryStateDisposition?: TraceableCarryStateDisposition"), "Traceable contract source is missing carry-state disposition metadata.");
  const extensionSource = await readFile(path.join(packageRoot, "src", "extension.ts"), "utf8");
  assert.ok(extensionSource.includes("async invoke(options: vscode.LanguageModelToolInvocationOptions<TInput>, token: vscode.CancellationToken)"), "Traceable extension source is missing cancellation-aware LM tool invoke wiring.");
  assert.ok(extensionSource.includes("this.invokeImpl(options.input, budget, preparedState, token)"), "Traceable extension source is missing token threading into queued tool invocations.");
  assert.ok(extensionSource.includes("prepareTraceableSubagentInput(input)"), "Traceable extension source is missing pre-run continuation preparation before export and execution.");
  assert.ok(extensionSource.includes("buildTraceableRequestSummary(effectiveInput)"), "Traceable extension source is missing request-summary rendering for the effective continuation input.");
  assert.ok(extensionSource.includes("Declared input mode: DIRECT"), "Traceable extension source is missing DIRECT mode summary rendering.");
  assert.ok(extensionSource.includes("Declared input mode: RESUME"), "Traceable extension source is missing RESUME mode summary rendering.");
  assert.ok(extensionSource.includes("label: \"Carry State\""), "Traceable extension source is missing the separate carry-state request summary item.");
  assert.ok(contractSource.includes("extractObservedReadTargets"), "Traceable contract source is missing observed-read target summaries.");
  console.log("ai-provenance vscode scaffold checks passed");
}

await main();